#!/usr/bin/perl -w
#
# ltag - List tags
#
# by Gregor N. Purdy (gregor@focusresearch.com)
#
# Copyright (C) 2000 Gregor N. Purdy. All rights reserved.
# This program is free software. It can be distributed under
# the same terms as Perl.
#

use strict;

use vars qw($VERSION);

$VERSION = '1.000';

my %tags;

open LOG, "cvs -q log -t |";

while (<LOG>) {
	next unless m/^symbolic names:/;

	while (<LOG>) {
		last if m/^keyword substitution:/;

		my ($tag, $rev) = /^\s*(.*): (.*)$/;

		$tags{$tag}++;
	}
}

print "$_\n" for sort { lc $a cmp lc $b } keys %tags;

exit 0;

__END__

=head1 NAME

ltag - List CVS tags

=head1 SYNOPSIS

B<ltag>

=head1 DESCRIPTION

Use B<ltag> in a CVS working directory to determine the
symbolic tags used at and below the current working directory.


=head1 OPTIONS

None.

=head1 AUTHOR

Gregor N. Purdy <gregor@focusresearch.com>

=head1 COPYRIGHT

Copyright (C) 2000 Gregor N. Purdy. All rights reserved.
This program is free software. It can be distributed under
the same terms as Perl.

=cut

#
# End of file.
#

